# Generated by Django 4.2.2 on 2023-07-05 07:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_exercisecategory_exercise_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='exercisecategory',
            options={'verbose_name_plural': 'Exercise  Categories'},
        ),
        migrations.RemoveField(
            model_name='exercise',
            name='video_url',
        ),
        migrations.AddField(
            model_name='exercise',
            name='video_embed',
            field=models.CharField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
    ]
