# Generated by Django 4.2.2 on 2023-07-12 07:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_workout_exercises_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='setlog',
            old_name='workou_exercise',
            new_name='workout_exercise',
        ),
    ]
